trigger:
  branches:
    include:
      - main
  paths:
    include:
      - host/src/

stages:
  - stage: BuildAndPublish
    jobs:
      - job: BuildAndPublishLinux
        displayName: 'Build and Publish on Linux'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UseDotNet@2
            inputs:
              version: '7.x'

          - task: DotnetCoreCLI@2
            displayName: 'Dotnet Publish'
            inputs:
              command: 'publish'
              publishWebProjects: false
              zipAfterPublish: false
              arguments: '-c Release -r linux-x64 -o $(Build.ArtifactStagingDirectory)/output/linux'
              workingDirectory: $(Build.SourcesDirectory)/host/src/FunctionsNetHost

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/output/linux'
              artifact: 'output'
              
      - job: BuildAndPublishWindows
        displayName: 'Build and Publish on Windows'
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: UseDotNet@2
            inputs:
              version: '7.x'

          - task: DotnetCoreCLI@2
            displayName: 'Dotnet Publish'
            inputs:
              command: 'publish'
              publishWebProjects: false
              zipAfterPublish: false
              arguments: '-c Release -r win-x64 -o $(Build.ArtifactStagingDirectory)/output/windows'
              workingDirectory: $(Build.SourcesDirectory)/host/src/FunctionsNetHost
          
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.ArtifactStagingDirectory)/output/windows'
              Contents: '**/*.exe'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/output/windows_filtered'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/output/windows_filtered'
              artifact: 'output_filtered'

  - stage: ConsolidateArtifacts
    displayName: 'Consolidate Artifacts'
    dependsOn: BuildAndPublish
    jobs:
      - job: ConsolidateArtifacts
        displayName: 'Consolidate Artifacts'
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: UseDotNet@2
            inputs:
              version: '7.x'

          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'output'
              path: '$(Build.ArtifactStagingDirectory)/output'
          
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'output_filtered'
              path: '$(Build.ArtifactStagingDirectory)/output_filtered'

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.ArtifactStagingDirectory)/output'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/dist/linux'

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.ArtifactStagingDirectory)/output_filtered'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/dist/windows'

          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $dirPath = "$(Build.ArtifactStagingDirectory)/dist"
                Get-ChildItem -Path $dirPath

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/dist'
              artifact: 'consolidated_output'
              publishLocation: 'pipeline'
